[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
betting_program = "cisSZzchpfV9kJTuqjSNeT7KZcv8dirUsb2kKcAAsyT"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
